### PR TITLE
fixes env set with commas (closes #14)

### LINKED ISSUE #14: Can't add environment variable that contains a comma
from https://github.com/jpignata/fargate/issues/40

### PR DESCRIPTION
**Pull request by jritsema**

### CODE REVIEW

File: cmd/service_env_set.go [hunk 1]
```diff
@@ -42,7 +42,7 @@ At least one environment variable must be specified via the --env flag. Specify
 }
 
 func init() {
-	serviceEnvSetCmd.Flags().StringSliceVarP(&flagServiceEnvSetEnvVars, "env", "e", []string{}, "Environment variables to set [e.g. KEY=value]")
+	serviceEnvSetCmd.Flags().StringArrayVarP(&flagServiceEnvSetEnvVars, "env", "e", []string{}, "Environment variables to set [e.g. KEY=value]")
```
Comment (mjreed-turner) [inline cmd/service_env_set.go]: OK, so this just eliminates the comma-separated-value functionality entirely; you have to specify the flag multiple times to set multiple vars. 👍

Comment (jritsema) [reply cmd/service_env_set.go]: Ya, the comma-separated functionality wasn't documented in help, so I thought it was ok to remove it :)
